[tool.poetry]
name = "web-app"
version = "0.0.1"
description = "HW"
authors = ["zhendler <zhendlerbing@gmail.com>"]
license = "y"
readme = "README.md"

[tool.poetry.dependencies]
flask = "^2.2.2"
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
